bootshelf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bootshelf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('webbooks.urls', namespace='webbooks')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django_comments_xtd.urls'))
)

webbooks/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout
from django.core.urlresolvers import reverse_lazy
from django.views.decorators.csrf import csrf_exempt

from webbooks import views

add_remove_book_ajax = login_required(csrf_exempt(views.AddRemoveBookAjaxView.as_view()), login_url=reverse_lazy('login'))
set_rating_ajax = login_required(csrf_exempt(views.SetRatingAjaxView.as_view()), login_url=reverse_lazy('login'))
delete_favorite_book_ajax = login_required(csrf_exempt(views.DeleteFavoriteDookAjax.as_view()), login_url=reverse_lazy('login'))

urlpatterns = patterns('',
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^registration/$', views.registration,  name='registration'),
    url(r'^$', views.BooksListView.as_view(), name='books_list'),
    url(r'^books/(?P<pk>\d+)/$', views.BookDetailView.as_view(), name='book_detail'),
    url(r'^profile/(?P<pk>\d+)/$', login_required(views.BooksProfileView.as_view()), name='book_profile'),

    #=== Ajax
    url(r'^add_remove_book_ajax/$', add_remove_book_ajax),
    url(r'^set_rating_ajax/$', set_rating_ajax),
    url(r'^delete_favorite_book_ajax/$', delete_favorite_book_ajax),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webbooks/models.py
from django.db import models
from django.contrib.auth.models import User

class Genre(models.Model):
    genre = models.CharField(max_length=60, unique=True)

    def __unicode__(self):
        return self.genre


class Books(models.Model):
    tittle = models.CharField(max_length=120)
    author = models.CharField(max_length=60)
    cover = models.ImageField(upload_to='books_images/')
    genre = models.ForeignKey(Genre)
    annotation = models.CharField(max_length=200)
    books_rating = models.ManyToManyField(User, through='BooksRating', related_name='books_rating')
    favourite_books = models.ManyToManyField(User, through='FavouriteBooks', related_name='favourite_books')

    def __unicode__(self):
        return self.tittle

class BooksRating(models.Model):
    books = models.ForeignKey(Books)
    user = models.ForeignKey(User)
    rating = models.DecimalField(max_digits=2, decimal_places=1)

    class Meta:
        unique_together = ('books', 'user',)

    def __unicode__(self):
        return u'%s %s' % (self.books, self.rating,)

class FavouriteBooks(models.Model):
    books = models.ForeignKey(Books)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.books

webbooks/forms.py
# -*- coding: utf-8
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email")

webbooks/views.py
import json
from django.views.generic import ListView, CreateView, DetailView, View
from django.shortcuts import redirect, render
from django.contrib import auth
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.db.models import Avg
from webbooks.models import Genre, Books, FavouriteBooks, BooksRating
from webbooks.forms import CreateNewUser



def registration(request):
    if request.method == 'POST':
        form = CreateNewUser(request.POST)
        if form.is_valid():
            form.save()
            user = auth.authenticate(username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password1'))
            auth.login(request, user)
            return HttpResponseRedirect('/')
    else:
        form = CreateNewUser()
    return render(request, 'registration/registration.html', {
        'form': form,
    })

class BooksListView(ListView):
    template_name = 'books_list.html'
    paginate_by = 6
    model = Books

    def get_queryset(self):
        genres_id = self.request.GET.get('genre')
        books = Books.objects.all()
        if genres_id:
            books = books.filter(genre__id=genres_id)
        return books


    def get_context_data(self, *args, **kwargs):
        context = super(BooksListView, self).get_context_data(*args, **kwargs)
        context['genres'] = Genre.objects.all()
        context['top'] = Books.objects.all()
        return context


class BookDetailView(DetailView):
    template_name = 'webbooks/books_details.html'
    context_object_name = 'book'
    model = Books

    def get_context_data(self, *args, **kwargs):
        context = super(BookDetailView, self).get_context_data(*args, **kwargs)
        context['genres'] = Genre.objects.all()
        context['top'] = Books.objects.all()
        return context


class BooksProfileView(ListView):
    model = Books
    template_name = 'webbooks/books_profile.html'
    paginate_by = 3

    def get_queryset(self):
        genres_id = self.request.GET.get('genre')
        books = User.objects.get(id=self.kwargs['pk']).favourite_books.all()
        if genres_id:
            books = books.filter(genre__id=genres_id)
        return books

    def get_context_data(self, *args, **kwargs):
        context = super(BooksProfileView, self).get_context_data(*args, **kwargs)
        context['genres'] = Genre.objects.all()
        context['top'] = Books.objects.all()
        return context

#=== ajax
class AddRemoveBookAjaxView(View):
    def post(self, *args, **kwargs):
        id = self.request.POST.get('id')
        polygons = self.request.POST.get('action')
        try:
            book = Books.objects.get(id=id)
            if polygons == "add":
                FavouriteBooks.objects.create(books=book, user=self.request.user)
            if polygons == "remove":
                FavouriteBooks.objects.filter(books=book, user=self.request.user).delete()
        except Books.DoesNotExist, FavouriteBooks.DoesNotExist:
            pass
        return HttpResponse('')

class SetRatingAjaxView(View):
    def post(self, *args, **kwargs):
        id = self.request.POST.get('id')
        rating_val = self.request.POST.get('rating_val')

        book = get_object_or_404(Books, pk=id)
        BooksRating.objects.update_or_create(books=book, user=self.request.user, defaults={'rating': rating_val})

        data = {
            'view': book.books_rating.count(),
            'mark': str(BooksRating.objects.get(books=book, user=self.request.user).rating),
            'total_mark': str(BooksRating.objects.filter(books=book).aggregate(Avg('rating'))['rating__avg'])
        }
        return HttpResponse(json.dumps(data), content_type="application/json")


class DeleteFavoriteDookAjax(View):
    def post(self, *args, **kwargs):
        book_id = self.request.POST.get('id')
        book = get_object_or_404(Books, pk=book_id)
        favourite_books = get_object_or_404(FavouriteBooks, books=book.id, user=self.request.user.id)
        favourite_books.delete()
        return HttpResponse("")

webbooks/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load books_tag %}

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Bookshelf</title>

    {% block base_css %}
    <!-- Bootstrap Core CSS -->
        <link href="{% static 'book_store/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'webbooks/css/template.css' %}" type="text/css" media="all" />

    {% endblock %}

    {% block rating_css %}
        <link href="{% static 'kartik_bootstrap_rating/css/star-rating.min.css' %}" rel="stylesheet">
    {% endblock %}

    {% block css %}{% endblock %}


</head>
<body>
    {% block nav_bar %}
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'webbooks:books_list' %}">Bookshelf</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <!--<li>-->
                        <!--<a href="#">About</a>-->
                    <!--</li>-->
                </ul>
                <div class="col-sm-3 col-md-3 pull-left">
                    <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Пошук" name="srch-term" id="srch-term">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                    </form>
                </div>
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a  href="{% url 'webbooks:book_profile' user.pk %}"><span class="glyphicon glyphicon-list"></span>Моя бібліотека</a>
                    </li>
                     <li> <a href="">Профіль: {{user}}</a></li>
                    <li><a href="{% url 'webbooks:logout' %}">Вихід</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'webbooks:registration' %}">Реєстрація</a></li>
                    <li class="dropdown">
                     <a href="http://www.jquery2dotnet.com" class="dropdown-toggle" data-toggle="dropdown">Вхід<b class="caret"></b></a>
                     <ul class="dropdown-menu" style="padding: 15px;min-width: 250px;">
                        <li>
                           <div class="row">
                              <div class="col-md-12">
                                 <form class="form" role="form" method="post" action="{% url 'webbooks:login' %}" accept-charset="UTF-8" id="login-nav">
                                    {% csrf_token %}
                                    <div class="form-group">
                                       <label class="sr-only" for="exampleInputEmail2">Email address</label>
                                       <input name="username" class="form-control" id="exampleInputEmail2" placeholder="login" required>
                                    </div>
                                    <div class="form-group">
                                       <label class="sr-only" for="exampleInputPassword2">Password</label>
                                       <input name="password" type="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
                                    </div>
                                    <div class="checkbox">
                                       <label>
                                       <input type="checkbox"> Remember me
                                       </label>
                                    </div>
                                    <div class="form-group">
                                       <button type="submit" class="btn btn-success btn-block">Sign in</button>
                                    </div>
                                 </form>
                              </div>
                           </div>
                        </li>
                     </ul>
                    </li>
                </ul>
                {% endif %}
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    {% endblock %}



    <!-- Page Content -->
    <div id="content" class="container">
        <div class="row">
            <div class="col-md-3">
                {% block genre %}
                <p class="lead">Категорії</p>
                <div class="list-group">
                    {% for genre in genres%}
                    <form action=".">

                        <a href="?genre={{genre.id}}" class="list-group-item">{{genre.genre}}</a>
                    </form>
                    {% endfor %}
                </div>
                {% endblock %}
            </div>

            <div class="col-md-9">
                {% block content %} {% endblock %}

                {% if is_paginated %}
                    <a href='?page=1' class="btn btn-success"><b>Перша</b></a>
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-success"><span class="glyphicon glyphicon-chevron-left"></span><span class="glyphicon glyphicon-chevron-left"></span></a>
                    {% endif %}
                    <div class="btn btn-success"><b>{{ page_obj.number }} - {{ page_obj.paginator.num_pages }}</b></div>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-success"><span class="glyphicon glyphicon-chevron-right"></span><span class="glyphicon glyphicon-chevron-right"></span></a>
                    {% endif %}
                    <a href='?page=last' class="btn btn-success"><b>Остання</b></a>
                {% endif %}
                <br><br>
                <div>
                    <h3>Top books</h3>
                    <div class="carousel slide" id="myCarousel">
                        <div class="carousel-inner">
                            <div class="item active">

                            </div>
                            {% for book in top %}
                            <div class="item">
                                <div class="col-xs-3 thumbnail">
                                    <img src="{{book.cover.url}}">
                                    <h4><a href="{% url 'webbooks:book_detail' book.id %}">{{book.tittle}}</a></h4>
                                        <p><b>Автор</b>: {{book.author}}</p>
                                        <p><b>Жанр</b>: {{book.genre}}</p>
                                        <p><b>Автор</b>: {{book.author}}</p>
                                    <div class="caption_anotation">
                                        <b>Опис:</b> <p>{{book.annotation}}</p>
                                    </div>
                                    <div id="rating"">
                                        <input id="input_rating"  name="{{book.id}}"  value='{{book|rating_books}}' class="rating" data-size="xs" step=0.5 data-readonly="True" >
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
                    </div>
                </div>
            </div>
        </div>

    </div>



    {% block base_js %}
            <!-- jQuery -->
        <script src="{% static 'book_store/js/jquery.js' %}"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'book_store/js/bootstrap.min.js' %}"></script>
    	<script type="text/javascript" src="{% static 'webbooks/js/template.js' %}"></script>
    {% endblock %}

    {% block rating_js %}
        <script src="{% static 'kartik_bootstrap_rating/js/star-rating.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'kartik_bootstrap_rating/js/my_rating.js' %}" type="text/javascript"></script>
    {% endblock %}

    {% block js %}{% endblock %}
</body>
</html>

webbooks/templates/comment/form.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

webbooks/templates/comment/list.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

webbooks/templates/comment/preview.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

webbooks/templates/webbooks/books_details.html
{% extends "base.html" %}
{% load staticfiles %}
{% load books_tag %}

{% load comments %}

{% block js %}
    <script type="text/javascript" src="{% static 'webbooks/js/books_ajax.js' %}"></script>
{% endblock %}

{% block css %}
    <!-- Custom CSS -->
    <link href="{% static 'blog_post/css/blog-post.css' %}">
    <link rel="stylesheet" href="{% static 'book_store/css/shop-homepage.css' %}" >
	<link rel="stylesheet" href="{% static 'webbooks/css/template.css' %}" type="text/css" media="all" />
{% endblock %}
{% block genre %}{% endblock %}
{% block content %}
    <p class="lead">{{book.tittle}}</p>
    <div id="books" class="thumbnail">
        <img src="{{book.cover.url}}">
        <h4><a href="{% url 'webbooks:book_detail' book.id %}">{{book.tittle}}</a></h4>
        <ul>
            <li>Автор: {{book.author}}</li>
            <li>Жанр: {{book.genre}}</li>
            <li>Автор: {{book.author}}</li>
        </ul>
        <div class="caption_anotation">
            <b>Опис:</b> <p>{{book.annotation}}</p>
        </div>
        <div id="rating"">
            <input id="input_rating"  name="{{book.id}}"  value='{{book|rating_books}}' class="rating" data-size="xs" step=0.5
                   {% if not user.is_authenticated %} data-readonly="True"  {% endif%} >
        </div>
        {% if user.is_authenticated %}
            <p id="rating_view" class="rating_view">
                <span name="you_mark">Ваша оцінка: {{book|you_rating_books:user}}</span>
                <span name="view" class="view">view({{book.books_rating.count}})</span>

            </p>
            {% if user in book.favourite_books.all %}
            <button type="button" id="{{book.id}}" name="remove" class="btn btn-link">remove</button>
            {% else %}
            <button type="button" id="{{book.id}}" name="add" class="btn btn-link">add</button>
            {% endif %}
        {% endif%}
    </div>



    <!-- Comments Form -->
    <div class="well">
        <h4>Leave a Comment:</h4>
        <form role="form">
            <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <hr>

    <!-- Posted Comments -->

    <!-- Comment -->
    <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="http://placehold.it/64x64" alt="">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Start Bootstrap
                <small>August 25, 2014 at 9:30 PM</small>
            </h4>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        </div>
    </div>

    <!-- Comment -->
    <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="http://placehold.it/64x64" alt="">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Start Bootstrap
                <small>August 25, 2014 at 9:30 PM</small>
            </h4>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            <!-- Nested Comment -->
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="http://placehold.it/64x64" alt="">
                </a>
                <div class="media-body">
                    <h4 class="media-heading">Nested Start Bootstrap
                        <small>August 25, 2014 at 9:30 PM</small>
                    </h4>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
            </div>
            <!-- End Nested Comment -->
        </div>
    </div>




<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}fluent_comments/css/ajaxcomments.css" />
<script type="text/javascript" src="{{ STATIC_URL }}fluent_comments/js/ajaxcomments.js"></script>

{% get_comment_count for book as comment_count %}
{% render_comment_list for book %}
{% render_comment_form for book %}

{% endblock %}

webbooks/templates/webbooks/books_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load books_tag %}


{% block js %}
	<script type="text/javascript" src="{% static 'webbooks/js/books_ajax.js' %}"></script>
{% endblock %}

{% block css %}
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'book_store/css/shop-homepage.css' %}" >
{% endblock %}



{% block content %}
    <p class="lead">Книги</p>
    <div id="books" class="row">
        {% if object_list %}
            {% for book in object_list %}
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">
                    <img src="{{book.cover.url}}">
                    <h4><a href="{% url 'webbooks:book_detail' book.id %}">{{book.tittle}}</a></h4>
                    <ul>
                        <li>Автор: {{book.author}}</li>
                        <li>Жанр: {{book.genre}}</li>
                        <li>Автор: {{book.author}}</li>
                    </ul>
                    <div class="caption_anotation">
                        <b>Опис:</b> <p>{{book.annotation}}</p>
                    </div>
                    <div id="rating"">
                        <input id="input_rating"  name="{{book.id}}"  value='{{book|rating_books}}' class="rating" data-size="xs" step=0.5 data-show-clear="false"
                               {% if not user.is_authenticated %} data-readonly="True"  {% endif%} >
                    </div>
                    {% if user.is_authenticated %}
                        <p id="rating_view" class="rating_view">
                            <span name="you_mark">Ваша оцінка: {{book|you_rating_books:user}}</span>
                            <span name="view" class="view">view({{book.books_rating.count}})</span>
                        </p>
                        {% if user in book.favourite_books.all %}
                        <button type="button" id="{{book.id}}" name="remove" class="btn btn-link">remove</button>
                        {% else %}
                        <button type="button" id="{{book.id}}" name="add" class="btn btn-link">add</button>
                        {% endif %}
                    {% endif%}
                </div>
            </div>
            {% endfor %}
        {% else %}
            <p>table is empty</p>
        {% endif %}
    </div>
{% endblock %}

webbooks/templates/webbooks/books_profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load books_tag %}

{% block js %}
	<script type="text/javascript" src="{% static 'webbooks/js/book_profile.js' %}"></script>
{% endblock %}



{% block css %}
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'book_store/css/shop-homepage.css' %}" >
	<link rel="stylesheet" href="{% static 'webbooks/css/template.css' %}" type="text/css" media="all" />
{% endblock %}
{% block content %}
    <p class="lead">Улюблені книги</p>
    <div id="books" class="row">
        {% if object_list %}
            {% for book in object_list %}
            <div id="book" class="col-sm-4 col-lg-4 col-md-4">
                <div id="thumbnail" class="thumbnail">
                    <img src="{{book.cover.url}}">
                    <h4><a href="{% url 'webbooks:book_detail' book.id %}">{{book.tittle}}</a></h4>
                    <ul>
                        <li>Автор: {{book.author}}</li>
                        <li>Жанр: {{book.genre}}</li>
                        <li>Автор: {{book.author}}</li>
                    </ul>
                    <div class="caption_anotation">
                        <b>Опис:</b> <p>{{book.annotation}}</p>
                    </div>
                    <div id="rating"">
                        <input id="input_rating"  name="{{book.id}}"  value='{{book|rating_books}}' class="rating" data-size="xs" step=0.5
                               {% if not user.is_authenticated %} data-readonly="True"  {% endif%} >
                    </div>
                    {% if user.is_authenticated %}
                        <p id="rating_view" class="rating_view">
                            <span name="you_mark">Ваша оцінка: {{book|you_rating_books:user}}</span>
                            <span name="view" class="view">view({{book.books_rating.count}})</span>

                        </p>
                        <button type="button" id="{{book.id}}" name="remove" class="btn btn-link">remove</button>
                    {% endif%}
                </div>
            </div>
            {% endfor %}
        {% else %}
            <p>table is empty</p>
        {% endif %}
    </div>
{% endblock %}